config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'home/about'

  devise_for :users
  resources :users, only: [:show, :index, :edit, :update] do
	get '/followers_list', to: 'relationships#followers_list'
  	get '/follows_list', to: 'relationships#follows_list'
  end

  resources :books do
    resource :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
    has_many :book_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy

    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
    belongs_to :book

    validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
  	belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :trackable,:validatable, authentication_keys: [:name]

	has_many :books, dependent: :destroy
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
	has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
	has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
	has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
	attachment :profile_image, destroy: false

	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	validates :name, length: {maximum: 20, minimum: 2}
	validates :introduction, length: { maximum: 50 }

	# ユーザーをフォローする
	def follow(user_id)
	  follower.create(followed_id: user_id)
	end

	# ユーザーのフォローを外す
	def unfollow(user_id)
	  follower.find_by(followed_id: user_id).destroy
	end

	# フォローしていればtrueを返す
	def following?(user)
	  following_user.include?(user)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	#デバイス機能実行前にconfigure_permitted_parametersの実行をする。
	protect_from_forgery with: :exception

  protected

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name, :introduction, :profile_image_id])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :name, :introduction, :profile_image_id])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    if comment.save
    	redirect_back(fallback_location: root_path)
    else
    	redirect_to book_path(book)
    end
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def show
  	@book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def index
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
    @book = Book.new
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @book.user_id = current_user.id
  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to book_path(id: @book.id), notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit
  	book = Book.find_by(id: params[:id])
    if book.user == current_user
      @book = book
    else
      redirect_to books_path and return
    end
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
    book = current_user.books.find(params[:id])
    if book.destroy
      redirect_to books_path, notice: "successfully delete book!"
    else
      redirect_to user_path(current_user)
    end
  end

  private

  def book_params
  	params.require(:book).permit(
      :title,
      :body
    )
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		book = Book.find(params[:book_id])
        favorite = current_user.favorites.new(book_id: book.id)
        favorite.save
        redirect_back(fallback_location: root_path)
	end
 	def destroy
 		book = Book.find(params[:book_id])
        favorite = current_user.favorites.find_by(book_id: book.id)
        favorite.destroy
        redirect_back(fallback_location: root_path)
  	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	def follow
	  current_user.follow(params[:id])
	  redirect_back(fallback_location: root_path)
	end

	def unfollow
	  current_user.unfollow(params[:id])
	  redirect_back(fallback_location: root_path)
	end

	def follows_list
	  @user = User.find(params[:user_id])
	  @users = User.all
	end

	def followers_list
	  @user = User.find(params[:user_id])
	  @users = User.all
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
	before_action :baria_user, only: [:update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def edit
  	user = User.find_by(id: params[:id])
    if user == current_user
      @user = current_user
    else
      redirect_to user_path(current_user) and return
    end
  end

  def update
   user = current_user
    if user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(user)
    else
      @user = user
      render :edit
    end
  end

  private

  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
  def baria_user
    unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class='container'>
	<div class="row">
	  <div class="col-md-6 col-md-offset-3">
		<% if @book.errors.any? %>
		  <div id="error_explanation">
			<h2><%= pluralize(@book.errors.count, "error") %></h2>
			<ul>
			<% @book.errors.full_messages.each do |message| %>
			  <li><%= message %></li>
			<% end %>
			</ul>
		  </div>
	    <% end %>

	<h1>Editing Book</h1>

	<%= render "books/newform", book: @book %>
	<%= link_to "Show", @book, class: "book_#{@book.id}" %>
	<%= link_to "Back", books_path, class: "back" %>

	</div>
	<div class="col-md-3"></div>

	</div>
</div>

app/views/books/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<% if @book.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@book.errors.count, "error") %></h2>
                <ul>
                <% @book.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>
			<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>

		</div>

		<div class="col-xs-9">
			<h2>Books index</h2>
			<!--books一覧 -->
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @books.each do |book| %>
						<tr>
							<td>
								<%= link_to(book.user) do %>
								<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
								<% end %>
							</td>
							<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
							<td><%= book.body %></td>
							<td>
								<% if book.favorited_by?(current_user) %>
									<ul>
										<%= link_to book_favorites_path(book), method: :delete do %>
	      									<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
	      									<%= book.favorites.count %> いいね
	    								<% end %>
	  								</ul>
								<% else %>
									<ul>
									    <%= link_to book_favorites_path(book), method: :post do %>
	     									<i class="fa fa-heart-o" aria-hidden="true"></i>
	      									<%= book.favorites.count %> いいね
	    								<% end %>
	  								</ul>
								<% end %>
							</td>

							<td>
								<p>コメント数：<%= book.book_comments.count %></p>
						    </td>
						</tr>
					<% end %>
				</tbody>
			</table>

			<!--books一覧 -->


		</div>
	</div>
</div>

app/views/books/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<% if flash[:notice] %>
				<div class="flash">
					<%= flash[:notice] %>
				</div>
			<% end %>

			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>

		</div>

		<div class="col-xs-9">
			<h2>Book detail</h2>

			<table class="table">
				<tr>
					<td>
						<%= link_to (@book.user) do %>
						<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, @book %></td>
					<td><%= @book.body %></td>
					<td>
						<% if @book.favorited_by?(current_user) %>
 							<ul>
								<%= link_to book_favorites_path(@book), method: :delete do %>
  									<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
  									<%= @book.favorites.count %> いいね
								<% end %>
							</ul>
						<% else %>
							<ul>
							    <%= link_to book_favorites_path(@book), method: :post do %>
 									<i class="fa fa-heart-o" aria-hidden="true"></i>
  									<%= @book.favorites.count %> いいね
								<% end %>
							</ul>
						<% end %>
					</td>
					<td>
						<p>コメント数：<%= @book.book_comments.count %></p>
					</td>
					<% if @book.user.id == current_user.id %>
						<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
						<td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>
				</tr>
			</table>

			<% @book.book_comments.each do |book_comment| %>
			  <span><%= book_comment.comment %></span>
			<% end %>

			<%= form_for [@book, @book_comment] do |f| %>
              <%= f.text_area :comment, rows: '5', class: "form-control",placeholder: "コメントをここに" %>
              <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
            <% end %>
		</div>
	</div>
</div>

app/views/home/about.html.erb
<h1>welcome to<span class="glyphicon glyphicon-book"></span>
<strong>Bookers</strong>  !!</h1>

app/views/home/top.html.erb
<div class="row">
	<div class="main col-md-offset-3 col-md-6">
		<h1>welcome to<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers</strong>  !!</h1>
			<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>

			<div class="btn-wrapper">
				<div class="row">
					<p><%=link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%=link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
				</div>
			</div>

	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--ヘッダーの記述-->
    <<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <!--if文でサインインとアウト時の表示を変更-->
            <% if user_signed_in? %>
              <li><%= link_to ' home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
              <li><%= link_to ' users', users_path, class: 'glyphicon glyphicon-user users' %></li>
              <li><%= link_to ' books', books_path, class: 'glyphicon glyphicon-book books' %></li>
              <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% else %>
              <li><%= link_to ' home', "/", class: 'glyphicon glyphicon-home home' %></li>
              <li><%= link_to ' about', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
              <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
              <li><%= link_to 'login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>

      </div>
    </header>
    <!--ヘッダーの記述-->
    <div class="container">
      <p id="notice"><%= notice %></p> <!--デバイスでnotice設定されているので呼び出してるだけ-->
      <%= yield %>
    </div>
  </body>
</html>

app/views/relationships/followers_list.html.erb
<h3>フォロワー一覧</h3>
<table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @user.follower_user.each do |user| %>
        <tr>
          <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
          <td><%= user.name%></td>
          <td><%= "フォロー数: #{user.follower.count}" %></td>
          <td><%= "フォロワー数: #{user.followed.count}" %></td>
          <td>
            <% if current_user.following?(user) %>
              <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
            <% else %>
              <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
            <% end %>
          </td>
          <td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

app/views/relationships/follows_list.html.erb
<h3>フォロー 一覧</h3>
<table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @user.following_user.each do |user| %>
        <tr>
          <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
          <td><%= user.name%></td>
          <td><%= "フォロー数: #{user.follower.count}" %></td>
          <td><%= "フォロワー数: #{user.followed.count}" %></td>
          <td>
            <% if current_user.following?(user) %>
              <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
            <% else %>
              <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
            <% end %>
          </td>
          <td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

app/views/users/_profile.html.erb
<table class="table">
		<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
		<tr>
			<th>follows</th>
			<th><%= link_to "#{user.follower.count}", user_follows_list_path(user_id: user.id) %></th>
		</tr>
		<tr>
			<th>followers</th>
			<th><%= link_to "#{user.followed.count}", user_followers_list_path(user_id: user.id) %></th>
		</tr>
		<tr>
			<th>
				<% unless user == current_user %>
	  				<% if current_user.following?(user) %>
	    				<%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
	  				<% else %>
	    				<%= link_to 'フォローする', follow_path(user.id), method: :POST %>
	  				<% end %>
				<% end %>
			</th>
		</tr>
</table>

<div class="row">
	<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %></h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :Name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :Image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :Introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

    <div class="col-xs-9">
		<h2>Users</h2>
		<!--users一覧 -->
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td><%= user.name%></td>
					<td><%= "フォロー数: #{user.follower.count}" %></td>
					<td><%= "フォロワー数: #{user.followed.count}" %></td>
					<td>
						<% unless @user == current_user %>
						  <% if current_user.following?(user) %>
						    <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
						  <% else %>
						    <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
						  <% end %>
						<% end %>
					</td>
					<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
    </div>
  </div>
</div>

		<!--users一覧 -->

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <% if flash[:notice] %>
        <div class="flash">
          <%= flash[:notice] %>
        </div>
      <% end %>
     </div>
  </div>
  <div class="row">
    <div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
		<!--同コントローラーのviewで表示ならusersは省略可 -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

    <div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to (book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td>
						<p>コメント数：<%= @book.book_comments.count %></p>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>